project:
  type: website
  output-dir: docs
  
website:
  navbar:
    title: "Rachel's Website"
    left:
      - text: Home
        href: index.qmd
      - text: FYP Project
        href: fyp-project.qmd
      - text: Travel Experience
        href: travel.qmd
      - text: Reflection
        href: reflection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left

editor: visual

